export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";

export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_POSTER = "CHANGE_POSTER";

export const ADD_MOVIE = "ADD_MOVIE";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE";
